config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'messages/create'
  resources :rooms do 
    resources :messages
  end
  
  resources :users
  root 'rooms#index'

  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  after_create_commit { broadcast_append_to self.room }
  before_create :confirm_participant

  def confirm_participant
    if self.room.is_private
      is_participant = Participant.where(user_id: self.user.id, room_id: self.room.id).first
      throw :abort unless is_participant
    end
  end
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, uniqueness: true
  scope :public_rooms, -> { where(is_private: false ) }
  # after_create_commit {broadcast_append_to "rooms"}

  has_many :messages
  has_many :participants, dependent: :destroy
  after_create_commit { broadcast_if_public }

  def broadcast_if_public
    broadcast_append_to "rooms" unless self.is_private
  end

  def self.create_private_room(users, room_name)
    single_room = Room.create(name: room_name, is_private: true)
    users.each do |user|
      Participant.create(user_id: user.id, room_id: single_room.id )
    end
    single_room
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness: true
  scope :all_except, ->(user) {where.not(id: user)}
  after_create_commit { broadcast_append_to "users" }

  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
  end

  def log_in(user)
    session[:user_id] = user.id
    @current_user = user 
    redirect_to root_path
  end 

  def logged_in?
    !current_user.nil?
  end 

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end 
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @current_user = current_user 
    @message = @current_user.messages.create(content: msg_params[:content], room_id: params[:room_id])
  end

  private 

  def msg_params 
    params.require(:message).permit(:content)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @current_user = current_user
    redirect_to '/signin' unless @current_user
    @rooms = Room.public_rooms
    @users = User.all_except(@current_user)
    @room = Room.new
  end

  def create 
    @room = Room.create(name: params["room"]["name"])
  end

  def show 
    @current_user = current_user
    @single_room = Room.find(params[:id])
    @rooms = Room.public_rooms
    @users = User.all_except(@current_user)
    @room = Room.new

    @message = Message.new

    @messages = @single_room.messages

    render :index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(username: params[:session][:username])
    if user
      log_in(user)
    else 
      render :new
    end 
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @current_user = current_user
    @rooms = Room.public_rooms
    @users = User.all_except(@current_user)
    @room = Room.new
    @message = Message.new
    @room_name = get_name(@user, @current_user)
    @single_room = Room.where(name: @room_name).first || Room.create_private_room([@user, @current_user], @room_name)
    @messages = @single_room.messages

    render "rooms/index"
  end

  private 
  def get_name(user1, user2)
    users = [user1, user2].sort
    "private#{users[0].id}_#{users[1].id}"
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_new_message_form.html.erb
<div class="form-group msg-form">
  <%= form_with(model: [@single_room ,@message], remote: true, class: "d-flex", data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" } ) do |f| %>
    <%= f.text_field :content, id: 'chat-text', class: "form-control msg-content", autocomplete: 'off' %>
    <%= f.submit data: { disable_with: false }, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/_new_room_form.html.erb
<%= form_with(model: @room, remote: true, class: "d-flex", data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" }) do |f| %>
  <%= f.text_field :name, class: "form-control", autocomplete: "Off" %>
  <%= f.submit data: {disable_with: false} %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <style>
      <%= ".msg-#{current_user&.id}" %> {
      background-color: #007bff !important;
      padding: 10px;
      }
      <%= ".cont-#{current_user&.id}" %> {
      display: flex;
      justify-content: flex-end
      }
    </style>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="cont-<%= message.user.id %>">
  <div class="message-box msg-<%= message.user.id %> " >
    <% unless message.room.is_private %>
      <h6 class="name"> <%= message.user.username %> </h6>
    <% end %>
  <%= message.content %>
  </div>
</div>

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/rooms/_room.html.erb
<div><%= link_to room.name, room %></div>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-md-2">
    <h5> Hi <%= @current_user.username %> </h5>
    <%= link_to 'Sign Out', signout_path,  :method => :delete %>
    <h4> Users </h4>
    <div>
      <%= turbo_stream_from "users" %>
      <div id="users">
        <%= render @users %>
      </div>
    </div>
    <h4> Rooms </h4>
    <%= render partial: "layouts/new_room_form" %>
    <div>
      <%= turbo_stream_from "rooms" %>
      <div id="rooms">
        <%= render @rooms %>
      </div>
    </div>
  </div>
  <div class="col-md-10 bg-dark text-light">
    <% if @single_room %>
      <h4 class="text-center"> <%= @user&.username || @single_room.name %> </h4>
      <%= turbo_stream_from @single_room %>
      <div id="messages">
        <%= render @messages %>
      </div>
      <%= render partial: 'layouts/new_message_form' %>
    <% end %>
  </div>
</div>
<%= link_to 'Sign Out', signout_path,  :method => :delete %>

app/views/users/_user.html.erb
<div><%= link_to user.username, user %></div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>